spring.application.name=FirstSpringBootlab9ex1
spring.datasource.url=jdbc:mysql://localhost:3306/bd_spring_jdbc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mamatata0!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=ALWAYS